services:
  base:
    build: ./dockerfile/base/.
    image: ${REPOSITORY_BUILD}/${BASE}
    init: true
    networks:
      - network

  apache:
    depends_on:
      # - postgresql
      - php
    build: ./dockerfile/apache/.
    image: ${REPOSITORY_BUILD}/${APACHE}
    init: true 
    networks:
      - network
    volumes:
      - type: bind
        source: ${DIR_LOCAL_SRC}
        target: ${DIR_CONTAINER_SRC}
      - type: bind
        source: ${DIR_LOCAL_DATA}
        target: ${DIR_CONTAINER_DATA}
      - type: bind
        source: ${LOCAL_SSL_CERT_KEY}
        target: ${CONTAINER_SSL_CERT_KEY}
      - type: bind
        source: ${LOCAL_SSL_PRIV_KEY}
        target: ${CONTAINER_SSL_PRIV_KEY}
    ports:
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
    restart: always
    environment:
      - SYMLINK_SRC=${DIR_CONTAINER_SRC}/public
      - SYMLINK_DST=/var/www/html/dnetv3
    stop_signal: SIGKILL

  php:
    build: ./dockerfile/php/.
    image: ${REPOSITORY_BUILD}/${PHP}
    init: true
    networks:
      - network
    volumes:
      - type: bind
        source: ${DIR_LOCAL_SRC}
        target: ${DIR_CONTAINER_SRC}
      - type: bind
        source: ${DIR_LOCAL_DATA}
        target: ${DIR_CONTAINER_DATA}
    restart: always
    environment:
      - SYMLINK_SRC=${DIR_CONTAINER_SRC}/public
      - SYMLINK_DST=/var/www/html/dnetv3

  postgresql:
    build: ./dockerfile/postgres_base/.
    image: ${REPOSITORY_BUILD}/${POSTGRESQL}
    init: true
    networks:
      - network
    volumes:
      - type: volume
        source: postgresql
        target: /var/lib/postgresql/data
    restart: always
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

  # vsftp:
  #   build: ./dockerfile/vsftp_base/.
  #   image: ${REPOSITORY_BUILD}/${VSFTP}
  #   init: true
  #   networks:
  #     - network
  #   volumes:
  #     - type: bind
  #       source: ${DIR_LOCAL_DATA}
  #       target: ${DIR_CONTAINER_DATA}
  #   restart: always
  #   ports:
  #     - "${PORT_FTP}:21"
  #     - "${PORT_FTP_PASV_START}-${PORT_FTP_PASV_END}:${PORT_FTP_PASV_START}-${PORT_FTP_PASV_END}"
  #   environment:
  #     - PASV_ADDRESS=${HOSTNAME:-localhost}
  #     - PASV_MIN_PORT=${PORT_FTP_PASV_START}
  #     - PASV_MAX_PORT=${PORT_FTP_PASV_END}

  # postfix:
  #   image: catatnight/postfix
  #   networks:
  #     - network
  #   environment:
  #     - maildomain=mail.example.com
  #     - smtp_user=user:pwd

  mailpit:
    image: axllent/mailpit:latest
    init: true
    networks:
      - network
    ports:
      - "${PORT_MAIL_WEBUI}:8025"
    environment:
      - MP_MAX_MESSAGES=1000  # 保存するメッセージの最大数
    restart: always


networks:
  network:

volumes:
  postgresql:
